---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: "Run a one-line script"
        run: "echo Hello, world!"
      -
        name: "running a custom scrip"
        run: "ls -al\n"
      -
        name: "Log in with Azure action"
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      -
        uses: azure/aks-set-context@v1
        with:
          cluster-name: githubactionaks
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          resource-group: githubRGACTION
      -
        run: "kubectl create namespace githubrg\n"
      -
        run: "kubectl apply -f .\n"
      -
        name: "RUN AZ COMMnd"
        run: |
          az account show
          az group list
      -
        if: always()
        name: "Run a multi-line script"
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      -
        name: "check java version"
        run: "java -version"
      -
        name: "gradle build"
        run: "gradle build"
      -
        name: "gradlew build"
        run: "./gradlew build"
      -
        name: "docker version"
        run: |
          docker -v
          docker
          docker images -a
      -
        name: "docker build"
        run: |
          docker build . -t shan0809/demo-kotlin2.0
          docker images -a
      -
        name: "docker login"
        run: "docker login -u ${{ secrets.dockerhubusername }} -p ${{ secrets.dockerhubpassword }}"
      -
        name: "docker image push"
        run: "docker push shan0809/demo-kotlin2.0"
name: "Continous Integration Demo"
true:
  push:
    branches:
      - main
      - feature/branch
  workflow_dispatch: ~
